language: node_js
dist: trusty
node_js: 8.11
sudo: true

addons:
  firefox: latest
  chrome: stable

# Add npm token to publish the package with `yarn release` command
# https://npme.npmjs.com/docs/workflow/travis.html#now-that-you-have-a-token
before_ install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc


# This is needed for the release script, namely for git checkout dist
# https://stackoverflow.com/a/47441734
install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --unshallow --tags
  - yarn

script:
  # xvfb-run is needed for headless testing with real browsers
  - if [[ "$TRAVIS_EVENT_TYPE" != "cron"  ]]; then
      xvfb-run yarn test;
    fi;

  - if [[ "$TRAVIS_EVENT_TYPE" = "cron"  ]]; then
      travis_retry yarn test:sauce &&
      yarn check:third-party;
    fi;

notifications:
  email:
    on_success: never

after_success:
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
      yarn release;
    fi;
  - cat ./coverage/lcov.info | coveralls
  - zip -r coverage.zip coverage
  - curl --upload-file ./coverage.zip https://transfer.sh/coverage.zip
